workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      - name: تنظيف المشروع
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods ios/.symlinks
          cd ios
          pod cache clean --all
          cd ..
          flutter pub get

      - name: تثبيت Pods
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: بناء التطبيق للمحاكي
        script: |
          flutter build ios --debug --simulator --verbose
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - tawheedkortam1@gmail.com