workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      - name: تنظيف وتجديد بيئة iOS بالكامل
        script: |
          echo "=== البدء في التنظيف العميق ==="
          # 1. تنظيف Flutter
          flutter clean
          flutter pub get

          # 2. حذف كل أثر لـ CocoaPods
          cd ios
          rm -rf Podfile.lock
          rm -rf Pods
          rm -rf .symlinks
          pod cache clean --all

          # 3. إعادة تثبيت Pods من الصفر مع التأكد من وجود Flutter
          pod deintegrate
          pod setup
          pod install --repo-update
          cd ..

          echo "=== التنظيف وإعادة التثبيت اكتمل ==="

      - name: بناء التطبيق للمحاكي
        script: |
          flutter build ios --debug --simulator --verbose
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - tawheedkortam1@gmail.com