// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8GXcXDjNZJcT2i7N6jUM3gTgZFeiP1o',
    appId: '1:45026720407:web:20dbdfabc13c29bb4507d2',
    messagingSenderId: '45026720407',
    projectId: 'missing-app-2026',
    authDomain: 'missing-app-2026.firebaseapp.com',
    storageBucket: 'missing-app-2026.firebasestorage.app',
    measurementId: 'G-Q85K1XZ523',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCBRH9jky3KKPnTCjgHT0wEyVZii1lUA',
    appId: '1:45026720407:android:ab7356dc15ff07714507d2',
    messagingSenderId: '45026720407',
    projectId: 'missing-app-2026',
    storageBucket: 'missing-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuauL6D9UngdXTB8nhaF0zjpCkWpSo38',
    appId: '1:45026720407:ios:461cbe0c152208e84507d2',
    messagingSenderId: '45026720407',
    projectId: 'missing-app-2026',
    storageBucket: 'missing-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.missingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvuauL6D9UngdXTB8nhaF0zjpCkWpSo38',
    appId: '1:45026720407:ios:461cbe0c152208e84507d2',
    messagingSenderId: '45026720407',
    projectId: 'missing-app-2026',
    storageBucket: 'missing-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.missingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_8GXcXDjNZJcT2i7N6jUM3gTgZFeiP1o',
    appId: '1:45026720407:web:29d329394c8ac9d54507d2',
    messagingSenderId: '45026720407',
    projectId: 'missing-app-2026',
    authDomain: 'missing-app-2026.firebaseapp.com',
    storageBucket: 'missing-app-2026.firebasestorage.app',
    measurementId: 'G-C6P3Z51416',
  );

}